// @flow

export const FETCH_USER_INFO_REQUEST = "FETCH_USER_INFO_REQUEST";
export const FETCH_USER_INFO_SUCCESS = "FETCH_USER_INFO_SUCCESS";
export const FETCH_USER_INFO_FAILURE = "FETCH_USER_INFO_FAILURE";
export const FETCH_USER_REPOSITORIES_REQUEST = "FETCH_USER_REPOSITORIES_REQUEST";
export const FETCH_USER_REPOSITORIES_SUCCESS = "FETCH_USER_REPOSITORIES_SUCCESS";
export const FETCH_USER_REPOSITORIES_FAILURE = "FETCH_USER_REPOSITORIES_FAILURE";